// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDje6joRyEprGK0uQ8PSKtqARkmgSfnOrY',
    appId: '1:552455772523:web:c6be1319b906fc1148d42e',
    messagingSenderId: '552455772523',
    projectId: 'pcstudioapp-b3e6f',
    authDomain: 'pcstudioapp-b3e6f.firebaseapp.com',
    storageBucket: 'pcstudioapp-b3e6f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbsFZ3WjJWmzV9oeps0MduaxdOlFrneUA',
    appId: '1:552455772523:android:e568d1cb6a460e2e48d42e',
    messagingSenderId: '552455772523',
    projectId: 'pcstudioapp-b3e6f',
    storageBucket: 'pcstudioapp-b3e6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXKu2CqpZVjkHIzqwHOzM6EYTNezy7EJ4',
    appId: '1:552455772523:ios:1890e9caa3fb605948d42e',
    messagingSenderId: '552455772523',
    projectId: 'pcstudioapp-b3e6f',
    storageBucket: 'pcstudioapp-b3e6f.firebasestorage.app',
    androidClientId: '552455772523-2gv6mu23sr6snl3h43c9cluc66gupr1e.apps.googleusercontent.com',
    iosClientId: '552455772523-r5n4c9jm72pad3j0p84r0a9e32vktg61.apps.googleusercontent.com',
    iosBundleId: 'com.example.appStudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXKu2CqpZVjkHIzqwHOzM6EYTNezy7EJ4',
    appId: '1:552455772523:ios:1890e9caa3fb605948d42e',
    messagingSenderId: '552455772523',
    projectId: 'pcstudioapp-b3e6f',
    storageBucket: 'pcstudioapp-b3e6f.firebasestorage.app',
    androidClientId: '552455772523-2gv6mu23sr6snl3h43c9cluc66gupr1e.apps.googleusercontent.com',
    iosClientId: '552455772523-r5n4c9jm72pad3j0p84r0a9e32vktg61.apps.googleusercontent.com',
    iosBundleId: 'com.example.appStudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDje6joRyEprGK0uQ8PSKtqARkmgSfnOrY',
    appId: '1:552455772523:web:b83b6e91c8bfb21248d42e',
    messagingSenderId: '552455772523',
    projectId: 'pcstudioapp-b3e6f',
    authDomain: 'pcstudioapp-b3e6f.firebaseapp.com',
    storageBucket: 'pcstudioapp-b3e6f.firebasestorage.app',
  );
}
